# Generated by Django 3.1.4 on 2021-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
